# Generated by Django 4.0.3 on 2022-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
